# Generated by Django 3.2.6 on 2021-09-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sending_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
